name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  redeploy_everything:
    name: Redeploying everything
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.111.34.204
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/draw-app
            git pull origin production
            export PATH=/home/ubuntu/.nvm/versions/node/v23.8.0/bin:$PATH
            pnpm install
            cd ~/draw-app/packages/db
            DATABASE_URL=${{ secrets.DATABASE_URL }} npx prisma migrate deploy
            DATABASE_URL=${{ secrets.DATABASE_URL }} npx prisma generate
            cd ~/draw-app
            pnpm run build
            pm2 restart fe
            pm2 restart ws
            pm2 restart http
